### ISSUE TITLE
Border braking the grid

### ISSUE THREAD

**Issue by anstapol** [GramThanos/jsCalendar#31]
Hi, nice plugin guys. Thanks for your job!

Problem:
Alignment doesn't match when there are rows with and without selected days.

<img width="297" alt="screenshot 2019-01-02 at 11 48 14" src="https://user-images.githubusercontent.com/33395021/50588902-83219980-0e84-11e9-95e1-b72f839d76f7.png">

Also line height is broken when any day of the month is selected.

Solve:
Just in case somebody needs this, here is the fix:

```scss
.jsCalendar tbody td.jsCalendar-selected {
   border: 2px solid currentColor;
   line-height: 2.2rem;
   cursor: pointer;
   height: 36px;
   width: 36px;
}
```

p.s.: It would be nice to have access to the sass files, just to do easier colours & sizes overrides.
